### ISSUE TITLE
hunger drains too quickly while sprinting

### ISSUE THREAD

**Issue by mmdk95** [cuberite/cuberite#2414]
it only takes seconds to drains the hunger while you're sprinting, (it doesn't happen always, sometimes it drains reasonably )

**Comment by tigerw** [comment]
It should be fixed by #2379, only if I could reach a development computer...

**Comment by Fighter19** [comment]
I tested it, but it doesn't only happen while sprinting, also normal walking or even sneaking is affected by that. (Still occurs with current build)

**Comment by jammet** [comment]
It still isn't fixed for going up and down ladders. I just updated a moment ago, climb a ladder, and starve trying to go all the way up to Block 254 or so. I'd probably run out of food twice or thrice on the way.

**Comment by tigerw** [comment]
Mah PR ain't merged yet :)

**Comment by jammet** [comment]
Time for a PR stunt. Bddm-tss! ;)

**Comment by tigerw** [comment]
:D

**Comment by SphinxC0re** [comment]
Close?

**Comment by jammet** [comment]
What? What? Is it fixed? :]

**Comment by SphinxC0re** [comment]
What about #2379?

**Comment by jammet** [comment]
I can confirm that hunger drain while climbing is fixed. :) Let's hope it
never comes back.
