### ISSUE TITLE
Tab list sometimes doesn't update

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#3138]
Sometimes, when a player leaves the server, their name stays in the online list that appears when pressing the tab key. This seems to happen randomly.

**Comment by bearbin** [comment]
I think this is fixed with the latest build. Could you confirm @mathias-github ?

**Comment by mathias-github** [comment]
This is not completely fixed yet. A player who joined and disconnected quickly didn't disappear from the tab list.
