### ISSUE TITLE
Jenkins OSX cmake command typo

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#4012]
The [OSX build](https://builds.cuberite.org/job/Cuberite%20OSX%20x64%20Master/322/console) seems to have a typo in the cmake command.
```
CMake Warning:
  Manually-specified variables were not used by the project:

    NO_NATIVE_OPTOMISATION
```

**Comment by bearbin** [comment]
Fixed.

**Comment by peterbell10** [comment]
I'm afraid it's still not fixed:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    NO_NATIVE_OPTIMISATION
```

It should have the American spelling: `NO_NATIVE_OPTIMIZATION`.

**Comment by bearbin** [comment]
Actually fixed this time...
